### ISSUE TITLE
Bugs when using petadmin and storage, others

### ISSUE THREAD

**Issue by ehetteNandaYo** [Jakllp/MyPet#41]
if you capture a baby pet, it gets converted to its adult version, when taking a pet out from the storage you an error.

taking pet from storage
https://paste.gg/p/anonymous/0e79113952a3471f91dd43d3cdd68211/files/788f9d04451642c3a3ae563055c38051/raw

Petadmin commands dont work like exp clone... 

petadmin clone
https://paste.gg/p/anonymous/36eff224519b4015a676836bf3a58b75/files/91fe2486a640440db003c34f27913f24/raw

cant change modes 
pb normal 
pb agroo 
pb farm

**Comment by Jakllp** [comment]
Some of this (exp, taking it from storage) seems to be entity-specific (this entity has specific attributes?)

Modes seem to be a general problem

**Comment by Jakllp** [comment]
@ehetteNandaYo is there anything special about the pet you wanted to take from  storage?

**Comment by Jakllp** [comment]
Fixed commands+storage in https://github.com/Jakllp/MyPet/commit/19c4b15203f171a98a6c6da99fd36deae6ee8625

Still waiting on info for baby-capture
Still working on behavior

**Comment by ehetteNandaYo** [comment]
> Some of this (exp, taking it from storage) seems to be entity-specific (this entity has specific attributes?)

> What baby-pet did you try to capture?

zombie, I will try other later when I try, 

I noticed because i had a db with pets from 1.16.5 and when I called it it was adult zombie, so I tried to capture another and same result

**Comment by Jakllp** [comment]
Alright.
I thibk I fixed the storage problem (will be in the next release) 

I triwd a baby pig and a baby chicken.
Will look into zombies later

**Comment by Jakllp** [comment]
Note to self: Baby Zombie might be due to new baby-system as baby zombies are different to other baby entities (might also effect piglins?)

**Comment by Jakllp** [comment]
Done in https://github.com/Jakllp/MyPet/commit/e7d2e38c8c214e6a892a0be4e9bd319efd6b678a

**Comment by Jakllp** [comment]
Forgot that behavior was still a thing

**Comment by Jakllp** [comment]
Behavior does work - Is skilltree-dependent - this might have been the cause for it not working on your end (or there was a bug that is now somehow fixed. Who knows)

**Comment by ehetteNandaYo** [comment]
petadmin exp still doesnt work

I tried it, it looks like it works but it doesnt, it didnt add set or remove any exp, it always stays the same

![image](https://user-images.githubusercontent.com/62739770/131237318-c1ea73ba-99e1-4796-a838-fd3413f88695.png)


if you try with a new pet it looks like this

![image](https://user-images.githubusercontent.com/62739770/131237302-743dc73a-bd40-47ab-b8cc-faf800ed82df.png)

**Comment by Jakllp** [comment]
@ehetteNandoYo I'm guessing you used these commands:
`/petadmin exp <PlayerName> 878` for first screenshot
`/petadmin exp <Playername> 0` for second screenshot

Or did you enter the command differently?

**Comment by ehetteNandaYo** [comment]
no, i was trying different numbers and all of them show the same result, I believe 878 is the exp the pet has at the moment, because a recently captured pet has 0

**Comment by Jakllp** [comment]
![image](https://user-images.githubusercontent.com/57708725/131259258-e25fd598-095b-41c7-aca2-9fa93afdbda5.png)
I gotta admit - I'm confused

I tried reproducing this error but the command works as I'd expect it to work - I don't know if other plugins are in play on your server (they technically shouldn't interfere with the exp-system tho)

The only way I found to get this result is by doing:
`/petadmin exp <Playername> set <number>`
The plugin expects the operator (in this case set) behind the amount (so: `/petadmin exp <Playername> <number> set`) which I gotta admit is odd.

The system technically works but the syntax can be improved (which I will do)

**Comment by ehetteNandaYo** [comment]
Ahhhh I was doing set number not number set which works... that was the issue...

**Comment by Jakllp** [comment]
Glad we could work it out ^^
